
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import *


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"/home/ali/Documents/gui_xcore/build/assets/frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("836x513")
window.configure(bg = "#0C0C0C")
window.resizable(False, False)

canvas = Canvas(window,bg = "#0C0C0C",height = 513,width = 836,bd = 0,highlightthickness = 0,relief = "ridge")

canvas.place(x = 0, y = 0)
button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
import_btn = Button(image=button_image_1,borderwidth=0,highlightthickness=0,command=lambda: print("button_1 clicked"),relief="flat")
import_btn.place(x=37.0,y=23.0,width=94.0,height=39.0)


button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
update_btn = Button(image=button_image_2,borderwidth=0,highlightthickness=0,command=lambda: print("button_2 clicked"),relief="flat")
update_btn.place(x=156.0,y=23.0,width=94.0,height=39.0)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
remove_btn = Button(image=button_image_3,borderwidth=0,highlightthickness=0,command=lambda: print("button_3 clicked"),relief="flat")
remove_btn.place(x=275.0,y=23.0,width=94.0,height=39.0)

button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
start_btn = Button(image=button_image_4,borderwidth=0,highlightthickness=0,command=lambda: print("button_4 clicked"),relief="flat")
start_btn.place(x=693.0,y=23.0,width=94.0,height=39.0)

canvas.create_rectangle(
    37.0,
    83.0,
    247.0,
    496.0,
    fill="#D9D9D9",
    outline="")

canvas.create_rectangle(
    275.0,
    83.0,
    787.0,
    351.0,
    fill="#D9D9D9",
    outline="")

canvas.create_rectangle(
    275.0,
    361.0,
    787.0,
    496.0,
    fill="#D9D9D9",
    outline="")

profile_list = Listbox(window,selectbackground="#2d9bf0",font=("Helvetica",15,"bold"))
profile_list.place(x=37,y=83,width=210,height=415)

profile_scroll = Scrollbar(window,orient=VERTICAL)
profile_scroll.place(x=251,y=83,width=20,height=415)


config_list = Listbox(window,selectbackground="#2d9bf0",font=("Helvetica",15,"bold"))
config_list.place(x=275,y=83,width=512,height=271)


consol = Text(window)
consol.place(x=275,y=361,width=512,height=137)


window.mainloop()
